export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_ERROR = 'LOGIN_ERROR';

export const FORGOT_SUCCESS = 'FORGOT_SUCCESS';
export const FORGOT_REQUEST = 'FORGOT_REQUEST';
export const FORGOT_ERROR = 'FORGOT_ERROR';

export const CHANGE_PASSWORD_SUCCESS = 'CHANGE_PASSWORD_SUCCESS';
export const CHANGE_PASSWORD_REQUEST = 'CHANGE_PASSWORD_REQUEST';
export const CHANGE_PASSWORD_ERROR = 'CHANGE_PASSWORD_ERROR';